import { useState, type FormEvent } from 'react';
import { CheckCircle2, Send, ShieldCheck } from 'lucide-react';
import './_group.css';
import { Field, GoflShell, QueuePreview, SectionHeading, formatDate, sessionFixture, sessionName, t } from './_shared';

type SubmissionForm = { artistName: string; songTitle: string; intro: string; genre: string; country: string; socialUrl: string; trackUrl: string };

export function CurrentSubmit() {
  const [sessionId, setSessionId] = useState(sessionFixture[0].id);
  const [form, setForm] = useState<SubmissionForm>({ artistName: '', songTitle: '', intro: '', genre: '', country: '', socialUrl: '', trackUrl: '' });
  const [rightsAccepted, setRightsAccepted] = useState(false);
  const [receipt, setReceipt] = useState<number | null>(null);
  const selected = sessionFixture.find((session) => session.id === sessionId);
  const update = (key: keyof SubmissionForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!sessionId || !rightsAccepted) return;
    setReceipt(5);
  };

  if (receipt !== null) return <GoflShell current="submit"><main className="mx-auto max-w-3xl px-4 py-16 sm:py-24"><div className="glass-panel rounded-2xl border border-primary/50 p-7 text-center shadow-[0_0_50px_hsl(267_89%_68%/.12)] sm:p-12"><CheckCircle2 className="mx-auto size-14 text-primary" /><p className="mt-6 font-mono-ui text-[10px] uppercase tracking-[.25em] text-primary">{t('submitted')}</p><h1 className="mt-3 font-display text-4xl">{t('receiptTitle')}</h1><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-muted-foreground">{t('receiptBody')}</p><div className="mx-auto mt-8 grid max-w-sm grid-cols-2 gap-3 text-left"><div className="rounded-lg border border-border bg-background/50 p-4"><span className="block text-[10px] uppercase tracking-wider text-muted-foreground">{t('queueNumber')}</span><strong className="mt-1 block font-mono-ui text-2xl text-primary">#{receipt}</strong></div><div className="rounded-lg border border-border bg-background/50 p-4"><span className="block text-[10px] uppercase tracking-wider text-muted-foreground">{t('status')}</span><strong className="mt-1 block text-sm text-foreground">{t('pending')}</strong></div></div><div className="mt-8 flex justify-center gap-3"><button type="button" onClick={() => setReceipt(null)} className="rounded-md border border-border px-4 py-3 text-xs font-bold uppercase tracking-wider hover:bg-secondary">{t('returnHome')}</button><a href="#sessions" className="rounded-md bg-primary px-4 py-3 text-xs font-bold uppercase tracking-wider text-primary-foreground">{t('viewSessions')}</a></div></div></main></GoflShell>;

  return <GoflShell current="submit"><main className="mx-auto max-w-[1180px] px-4 py-12 sm:px-7 sm:py-16"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><SectionHeading eyebrow={t('submit')} title={t('submitTitle')} body={t('submitBody')} /><form onSubmit={onSubmit} className="mt-8 space-y-5 rounded-xl border border-border bg-card/35 p-5 sm:p-8" data-testid="form-submit-track">
    <div className="grid gap-5 sm:grid-cols-2"><Field label={t('artist')} required value={form.artistName} onChange={(v) => update('artistName', v)} placeholder={t('artistPlaceholder')} /><Field label={t('song')} required value={form.songTitle} onChange={(v) => update('songTitle', v)} placeholder={t('songPlaceholder')} /></div>
    <div><label className="mb-2 flex justify-between text-xs font-bold uppercase tracking-wider text-foreground">{t('intro')}<span className="font-mono-ui text-[10px] font-normal text-muted-foreground">{form.intro.length}/300</span></label><textarea required maxLength={300} value={form.intro} onChange={(e) => update('intro', e.target.value)} placeholder={t('introHint')} className="min-h-28 w-full resize-y rounded-md border border-input bg-background/60 px-3 py-3 text-sm outline-none transition placeholder:text-muted-foreground/70 focus:border-primary focus:ring-2 focus:ring-primary/20" data-testid="input-intro" /></div>
    <div className="grid gap-5 sm:grid-cols-2"><Field label={t('genre')} required value={form.genre} onChange={(v) => update('genre', v)} placeholder={t('genrePlaceholder')} /><Field label={t('country')} required value={form.country} onChange={(v) => update('country', v)} placeholder={t('countryPlaceholder')} /></div>
    <div className="grid gap-5 sm:grid-cols-2"><Field label={t('social')} value={form.socialUrl} onChange={(v) => update('socialUrl', v)} placeholder={t('urlPlaceholder')} type="url" /><Field label={t('track')} required value={form.trackUrl} onChange={(v) => update('trackUrl', v)} placeholder={t('urlPlaceholder')} type="url" /></div>
    <div><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-foreground">{t('chooseSession')} <span className="text-accent">*</span></label><select required value={sessionId} onChange={(e) => setSessionId(e.target.value)} className="w-full rounded-md border border-input bg-background/60 px-3 py-3 text-sm outline-none focus:border-primary" data-testid="select-session">{sessionFixture.map((session) => <option key={session.id} value={session.id} disabled={!session.isOpen || session.available < 1}>{sessionName(session)} · {formatDate(session.startsAt, { weekday: 'short' })} · {session.available} {t('available')}</option>)}</select>{selected && !selected.isOpen && <p className="mt-2 text-xs text-destructive">{t('sessionClosed')}</p>}</div>
    <label className="flex cursor-pointer items-start gap-3 rounded-md border border-border bg-background/35 p-3 text-xs leading-5 text-muted-foreground"><input type="checkbox" checked={rightsAccepted} onChange={(e) => setRightsAccepted(e.target.checked)} className="mt-1 size-4 accent-[hsl(var(--primary))]" data-testid="input-rights-accepted" /><span>{t('rights')} <span className="text-accent">*</span></span></label>
    <button type="submit" className="flex w-full items-center justify-center gap-2 rounded-md bg-primary px-4 py-3.5 text-xs font-bold uppercase tracking-[.18em] text-primary-foreground transition hover:bg-primary/85 disabled:cursor-not-allowed disabled:opacity-50" data-testid="button-submit-track"><Send className="size-4" />{t('sendTrack')}</button>
  </form></div><aside className="space-y-5"><div className="rounded-xl border border-primary/30 bg-primary/5 p-6"><ShieldCheck className="size-6 text-primary" /><h2 className="mt-5 font-display text-2xl">{t('howItWorks')}</h2><div className="mt-6 space-y-5">{[['step1', 'step1Body'], ['step2', 'step2Body'], ['step3', 'step3Body']].map(([title, body], i) => <div key={title} className="flex gap-3"><span className="font-mono-ui text-xs text-accent">0{i + 1}</span><div><h3 className="text-sm font-bold">{t(title)}</h3><p className="mt-1 text-xs leading-6 text-muted-foreground">{t(body)}</p></div></div>)}</div></div><QueuePreview /></aside></div></main></GoflShell>;
}

export default CurrentSubmit;