import { useEffect, useMemo, useState } from 'react';
import { AudioLines, Check, ChevronLeft, Headphones, ListMusic, Mic2, Pause, Play, SkipForward } from 'lucide-react';
import './_group.css';
import { GoflShell, queueFixture, t, type GoFLQueueItem } from './_shared';

function MockTrackPlayer({ playing, onToggle }: { playing: boolean; onToggle: () => void }) {
  return <div className="mt-5 overflow-hidden rounded-lg border border-border bg-background/60" aria-label={t('embeddedPlayer')}>
    <div className="flex items-center gap-4 p-4"><button type="button" onClick={onToggle} aria-label={playing ? t('pause') : t('play')} className="grid size-10 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground">{playing ? <Pause className="size-4" /> : <Play className="ml-0.5 size-4 fill-current" />}</button><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><AudioLines className="size-4 text-primary" /><span className="truncate text-xs font-bold uppercase tracking-wider text-foreground">Gathering of the Fallen · Live</span></div><div className="mt-3 h-1 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full bg-gradient-to-r from-primary to-accent ${playing ? 'w-2/5' : 'w-1/5'}`} /></div><div className="mt-1 flex justify-between font-mono-ui text-[9px] text-muted-foreground"><span>{playing ? '1:24' : '0:00'}</span><span>4:12</span></div></div></div>
  </div>;
}

export function CurrentLive() {
  const [queue, setQueue] = useState(queueFixture);
  const [playing, setPlaying] = useState(false);
  const ordered = useMemo(() => queue.filter((item) => item.status === 'approved' || item.status === 'played' || item.status === 'skipped').sort((a, b) => a.queueNumber - b.queueNumber), [queue]);
  const current = useMemo(() => queue.filter((item) => item.status === 'approved').sort((a, b) => a.queueNumber - b.queueNumber)[0], [queue]);
  const currentPosition = current ? ordered.findIndex((item) => item.id === current.id) + 1 : 0;
  const nextItems = current ? queue.filter((item) => item.status === 'approved' && item.queueNumber > current.queueNumber).sort((a, b) => a.queueNumber - b.queueNumber).slice(0, 3) : [];
  useEffect(() => setPlaying(false), [current?.id]);
  const status = (id: string, value: 'played' | 'skipped') => {
    setQueue((items) => items.map((item) => item.id === id ? { ...item, status: value } : item));
    setPlaying(false);
  };

  return <GoflShell current="live"><main className="mx-auto max-w-[1440px] px-4 py-9 sm:px-7 sm:py-12">
    <div className="flex flex-wrap items-center justify-between gap-4 border-b border-border/70 pb-6"><div className="flex items-center gap-3"><span className="size-3 animate-live rounded-full bg-accent" /><div><p className="font-mono-ui text-[10px] uppercase tracking-[.24em] text-accent">On air</p><h1 className="mt-1 font-display text-3xl">{t('live')}</h1></div></div><a href="#host" className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-muted-foreground hover:text-foreground"><ChevronLeft className="size-4" />{t('admin')}</a></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_340px]"><section>
      <div className="glass-panel rounded-2xl border border-primary/45 p-5 sm:p-8"><div className="flex items-center justify-between"><span className="font-mono-ui text-xs text-primary">{current ? `${t('trackOf')} ${String(currentPosition).padStart(2, '0')} / ${String(ordered.length).padStart(2, '0')}` : t('upcoming')}</span><AudioLines className="size-5 text-primary" /></div>
        {current ? <><div className="mt-7 grid gap-5 sm:grid-cols-[170px_1fr] sm:items-center"><div className="grid aspect-square place-items-center rounded-xl border border-primary/30 bg-[radial-gradient(circle_at_40%_30%,hsl(326_89%_65%/.28),transparent_35%),linear-gradient(145deg,hsl(231_39%_17%),hsl(229_42%_5%))] shadow-[0_0_35px_hsl(267_89%_68%/.1)]"><Headphones className="size-14 text-primary/70" /></div><div><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-accent">{t('nowPlaying')}</p><h2 className="mt-2 font-display text-4xl leading-tight sm:text-5xl">{current.artistName}</h2><p className="mt-2 text-xl text-foreground">{current.songTitle}</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full border border-border px-2.5 py-1 text-[10px] text-muted-foreground">{current.genre}</span><span className="rounded-full border border-border px-2.5 py-1 text-[10px] text-muted-foreground">{current.country}</span></div><p className="mt-4 max-w-xl text-sm leading-7 text-muted-foreground">{current.intro}</p><MockTrackPlayer playing={playing} onToggle={() => setPlaying((value) => !value)} /></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><button type="button" onClick={() => setPlaying((value) => !value)} className="flex items-center justify-center gap-2 rounded-md bg-primary py-4 text-xs font-bold uppercase tracking-wider text-primary-foreground hover:bg-primary/85">{playing ? <Pause className="size-5" /> : <Play className="size-5 fill-current" />}{playing ? t('pause') : t('play')}</button><button type="button" onClick={() => status(current.id, 'skipped')} className="flex items-center justify-center gap-2 rounded-md border border-primary/40 bg-primary/5 py-4 text-xs font-bold uppercase tracking-wider text-foreground hover:bg-primary/10"><SkipForward className="size-5" />{t('next')}</button><button type="button" onClick={() => status(current.id, 'played')} className="flex items-center justify-center gap-2 rounded-md border border-accent/50 bg-accent/10 py-4 text-xs font-bold uppercase tracking-wider text-accent hover:bg-accent/15"><Check className="size-5" />{t('markPlayed')}</button></div></> : <div className="py-16 text-center"><ListMusic className="mx-auto size-10 text-primary" /><h2 className="mt-5 font-display text-2xl">{t('emptyQueue')}</h2><p className="mt-2 text-sm text-muted-foreground">{t('emptyQueueBody')}</p></div>}
      </div>
      <div className="mt-5 rounded-xl border border-border bg-card/25 p-5"><div className="flex items-center justify-between"><h2 className="font-display text-xl">{t('upcoming')}</h2><span className="font-mono-ui text-[10px] uppercase tracking-wider text-muted-foreground">{nextItems.length} {t('trackOf')}</span></div>{nextItems.length > 0 && <div className="mt-4 divide-y divide-border/70">{nextItems.map((item: GoFLQueueItem) => <div key={item.id} className="flex items-center gap-3 py-3"><span className="w-7 font-mono-ui text-xs text-primary">{String(item.queueNumber).padStart(2, '0')}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.songTitle}</strong><span className="block truncate text-xs text-muted-foreground">{item.artistName}</span></div><span className="rounded-full border border-border px-2 py-1 text-[10px] text-muted-foreground">{item.genre}</span></div>)}</div>}</div>
    </section><aside className="space-y-5"><div className="rounded-xl border border-border bg-card/35 p-6"><p className="font-mono-ui text-[10px] uppercase tracking-[.24em] text-primary">{t('hostGuide')}</p><div className="mt-5 space-y-4">{[['guide1', 'guideBody1'], ['guide2', 'guideBody2'], ['guide3', 'guideBody3'], ['guide4', 'guideBody4']].map(([title, body], i) => <div className="flex gap-3" key={title}><span className="grid size-7 shrink-0 place-items-center rounded-full border border-primary/50 font-mono-ui text-xs text-primary">{i + 1}</span><div><strong className="text-sm">{t(title)}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{t(body)}</p></div></div>)}</div></div><div className="rounded-xl border border-accent/25 bg-accent/5 p-6"><Mic2 className="size-5 text-accent" /><p className="mt-4 text-sm leading-6 text-muted-foreground">{t('submitNote')}</p></div></aside></div>
  </main></GoflShell>;
}

export default CurrentLive;